# permissions for end users to view argorolloutconfigkeeperclusterscopes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: argorolloutconfigkeeperclusterscope-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: argo-rollout-config-keeper
    app.kubernetes.io/part-of: argo-rollout-config-keeper
    app.kubernetes.io/managed-by: kustomize
  name: argorolloutconfigkeeperclusterscope-viewer-role
rules:
- apiGroups:
  - configkeeper.run.ai
  resources:
  - argorolloutconfigkeeperclusterscopes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configkeeper.run.ai
  resources:
  - argorolloutconfigkeeperclusterscopes/status
  verbs:
  - get
