//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoRolloutConfigKeeper) DeepCopyInto(out *ArgoRolloutConfigKeeper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoRolloutConfigKeeper.
func (in *ArgoRolloutConfigKeeper) DeepCopy() *ArgoRolloutConfigKeeper {
	if in == nil {
		return nil
	}
	out := new(ArgoRolloutConfigKeeper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoRolloutConfigKeeper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoRolloutConfigKeeperClusterScope) DeepCopyInto(out *ArgoRolloutConfigKeeperClusterScope) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoRolloutConfigKeeperClusterScope.
func (in *ArgoRolloutConfigKeeperClusterScope) DeepCopy() *ArgoRolloutConfigKeeperClusterScope {
	if in == nil {
		return nil
	}
	out := new(ArgoRolloutConfigKeeperClusterScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoRolloutConfigKeeperClusterScope) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoRolloutConfigKeeperClusterScopeList) DeepCopyInto(out *ArgoRolloutConfigKeeperClusterScopeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArgoRolloutConfigKeeperClusterScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoRolloutConfigKeeperClusterScopeList.
func (in *ArgoRolloutConfigKeeperClusterScopeList) DeepCopy() *ArgoRolloutConfigKeeperClusterScopeList {
	if in == nil {
		return nil
	}
	out := new(ArgoRolloutConfigKeeperClusterScopeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoRolloutConfigKeeperClusterScopeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoRolloutConfigKeeperClusterScopeSpec) DeepCopyInto(out *ArgoRolloutConfigKeeperClusterScopeSpec) {
	*out = *in
	if in.ConfigLabelSelector != nil {
		in, out := &in.ConfigLabelSelector, &out.ConfigLabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IgnoredNamespaces != nil {
		in, out := &in.IgnoredNamespaces, &out.IgnoredNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoRolloutConfigKeeperClusterScopeSpec.
func (in *ArgoRolloutConfigKeeperClusterScopeSpec) DeepCopy() *ArgoRolloutConfigKeeperClusterScopeSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoRolloutConfigKeeperClusterScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoRolloutConfigKeeperClusterScopeStatus) DeepCopyInto(out *ArgoRolloutConfigKeeperClusterScopeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoRolloutConfigKeeperClusterScopeStatus.
func (in *ArgoRolloutConfigKeeperClusterScopeStatus) DeepCopy() *ArgoRolloutConfigKeeperClusterScopeStatus {
	if in == nil {
		return nil
	}
	out := new(ArgoRolloutConfigKeeperClusterScopeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoRolloutConfigKeeperList) DeepCopyInto(out *ArgoRolloutConfigKeeperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArgoRolloutConfigKeeper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoRolloutConfigKeeperList.
func (in *ArgoRolloutConfigKeeperList) DeepCopy() *ArgoRolloutConfigKeeperList {
	if in == nil {
		return nil
	}
	out := new(ArgoRolloutConfigKeeperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoRolloutConfigKeeperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoRolloutConfigKeeperSpec) DeepCopyInto(out *ArgoRolloutConfigKeeperSpec) {
	*out = *in
	if in.ConfigLabelSelector != nil {
		in, out := &in.ConfigLabelSelector, &out.ConfigLabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoRolloutConfigKeeperSpec.
func (in *ArgoRolloutConfigKeeperSpec) DeepCopy() *ArgoRolloutConfigKeeperSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoRolloutConfigKeeperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoRolloutConfigKeeperStatus) DeepCopyInto(out *ArgoRolloutConfigKeeperStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoRolloutConfigKeeperStatus.
func (in *ArgoRolloutConfigKeeperStatus) DeepCopy() *ArgoRolloutConfigKeeperStatus {
	if in == nil {
		return nil
	}
	out := new(ArgoRolloutConfigKeeperStatus)
	in.DeepCopyInto(out)
	return out
}
