{
 "title": "Argo-rollout-config-keeper",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(argo_rollout_config_keeper_configmap_reconcile_duration_seconds_count,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Managed ConfigMaps ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_rollout_config_keeper_managed_configmap_count{cluster=\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Managed Secrets",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_rollout_config_keeper_managed_secret_count{cluster=\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "ConfigMaps - discovered vs managed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "argo_rollout_config_keeper_discovered_configmap_count{cluster=\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "argo_rollout_config_keeper_managed_configmap_count{cluster=\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Secrets - discovered vs managed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "argo_rollout_config_keeper_discovered_secret_count{cluster=\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "argo_rollout_config_keeper_managed_secret_count{cluster=\"$cluster\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}