name: "Argo-rollout-config-keeper CI: release"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release_artifact:
    name: Release Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact to release
        uses: Shopify/upload-to-release@v1
        with:
          name: argo-rollout-config-keeper-operator.yaml
          path: argo-rollout-config-keeper-operator.yaml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: text/plain

  release_image:
    name: Release Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Make fmt
        run: make fmt

      - name: Make lint
        run: make lint

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          make docker-build docker-push IMG="${{ secrets.DOCKERHUB_USERNAME }}/argo-rollout-config-keeper-operator:v${{ github.ref_name }}"
